name: JACUSA2pipeline_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake=6.8.1
  - samtools=1.12
  - openjdk=10.0.2
  - Minimap2=2.22
  - r-base=4.0.5
  - bedtools=2.29.2
  - r-NMF=0.24.0 
  - r-ggplot2=3.3.6
  - r-pROC=_1.4.0
  - r-stringr=1.4.0

